[2024-05-25T19:10:09.673+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:10:09.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T19:10:09.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T19:10:09.705+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:10:09.719+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): first-step-el> on 2024-05-25 00:00:00+00:00
[2024-05-25T19:10:09.726+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=836) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:10:09.728+0000] {standard_task_runner.py:63} INFO - Started process 838 to run task
[2024-05-25T19:10:09.728+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'first-step-el', 'scheduled__2024-05-25T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpvg34kbqt']
[2024-05-25T19:10:09.729+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask first-step-el
[2024-05-25T19:10:09.793+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [running]> on host 328b16f677f9
[2024-05-25T19:10:09.899+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='first-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:00:00+00:00'
[2024-05-25T19:10:09.901+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:10:09.901+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:10:09.902+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: step_ingesta_carga_pura() missing 1 required positional argument: 'password'
[2024-05-25T19:10:09.909+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=DAG_catedra_***, task_id=first-step-el, run_id=scheduled__2024-05-25T00:00:00+00:00, execution_date=20240525T000000, start_date=20240525T191009, end_date=20240525T191009
[2024-05-25T19:10:09.922+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task first-step-el (step_ingesta_carga_pura() missing 1 required positional argument: 'password'; 838)
[2024-05-25T19:10:09.942+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:10:09.960+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T19:10:09.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-25T19:59:07.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T19:59:07.384+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T19:59:07.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T19:59:07.396+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T19:59:07.415+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): first-step-el> on 2024-05-25 00:00:00+00:00
[2024-05-25T19:59:07.423+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1410) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T19:59:07.425+0000] {standard_task_runner.py:63} INFO - Started process 1419 to run task
[2024-05-25T19:59:07.426+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'first-step-el', 'scheduled__2024-05-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmp8w7lkszv']
[2024-05-25T19:59:07.427+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask first-step-el
[2024-05-25T19:59:07.510+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [running]> on host 328b16f677f9
[2024-05-25T19:59:07.739+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='first-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:00:00+00:00'
[2024-05-25T19:59:07.743+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T19:59:07.902+0000] {logging_mixin.py:188} INFO - ERROR, CANNOT CONNECT TO DATABASE
[2024-05-25T19:59:07.903+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T19:59:07.904+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/Steps.py", line 7, in step_ingesta_carga_pura
    df=functions.SQL_query(host_1,database,user,password,port,extract_query,column_names_e)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/functions.py", line 21, in SQL_query
    conn=connectionSQL(host,database,user,password,port)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/functions.py", line 17, in connectionSQL
    return conn
           ^^^^
UnboundLocalError: cannot access local variable 'conn' where it is not associated with a value
[2024-05-25T19:59:07.950+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=DAG_catedra_***, task_id=first-step-el, run_id=scheduled__2024-05-25T00:00:00+00:00, execution_date=20240525T000000, start_date=20240525T195907, end_date=20240525T195907
[2024-05-25T19:59:07.991+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task first-step-el (cannot access local variable 'conn' where it is not associated with a value; 1419)
[2024-05-25T19:59:08.062+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T19:59:08.103+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T19:59:08.116+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-25T20:43:42.257+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T20:43:42.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T20:43:42.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T20:43:42.295+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T20:43:42.312+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): first-step-el> on 2024-05-25 00:00:00+00:00
[2024-05-25T20:43:42.319+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T20:43:42.321+0000] {standard_task_runner.py:63} INFO - Started process 235 to run task
[2024-05-25T20:43:42.321+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'first-step-el', 'scheduled__2024-05-25T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpkc8gb84y']
[2024-05-25T20:43:42.323+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask first-step-el
[2024-05-25T20:43:42.381+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [running]> on host d4c9de26d10f
[2024-05-25T20:43:42.490+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='first-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:00:00+00:00'
[2024-05-25T20:43:42.492+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T20:43:42.562+0000] {logging_mixin.py:188} INFO - ERROR, CANNOT CONNECT TO DATABASE
[2024-05-25T20:43:42.563+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T20:43:42.565+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/Steps.py", line 7, in step_ingesta_carga_pura
    df=functions.SQL_query(host_1,database,user,password,port,extract_query,column_names_e)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/functions.py", line 21, in SQL_query
    conn=connectionSQL(host,database,user,password,port)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/functions.py", line 17, in connectionSQL
    return conn
           ^^^^
UnboundLocalError: cannot access local variable 'conn' where it is not associated with a value
[2024-05-25T20:43:42.579+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=DAG_catedra_***, task_id=first-step-el, run_id=scheduled__2024-05-25T00:00:00+00:00, execution_date=20240525T000000, start_date=20240525T204342, end_date=20240525T204342
[2024-05-25T20:43:42.609+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task first-step-el (cannot access local variable 'conn' where it is not associated with a value; 235)
[2024-05-25T20:43:42.657+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T20:43:42.729+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T20:43:42.752+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-25T21:12:01.297+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T21:12:01.321+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T21:12:01.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [queued]>
[2024-05-25T21:12:01.329+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-25T21:12:01.342+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): first-step-el> on 2024-05-25 00:00:00+00:00
[2024-05-25T21:12:01.349+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=116) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T21:12:01.350+0000] {standard_task_runner.py:63} INFO - Started process 118 to run task
[2024-05-25T21:12:01.351+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'first-step-el', 'scheduled__2024-05-25T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmp6afb3i3h']
[2024-05-25T21:12:01.352+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask first-step-el
[2024-05-25T21:12:01.395+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.first-step-el scheduled__2024-05-25T00:00:00+00:00 [running]> on host b2cfee8f0b2b
[2024-05-25T21:12:01.471+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='first-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T00:00:00+00:00'
[2024-05-25T21:12:01.473+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T21:12:01.479+0000] {logging_mixin.py:188} INFO - Connection to database was succesful
[2024-05-25T21:12:01.498+0000] {logging_mixin.py:188} INFO - Query completed
[2024-05-25T21:12:01.501+0000] {logging_mixin.py:188} INFO - execute_query_result_set()
[2024-05-25T21:12:01.506+0000] {logging_mixin.py:188} INFO - Connection to database was succesful
[2024-05-25T21:12:01.512+0000] {logging_mixin.py:188} INFO - Inserts performed wihout fail
[2024-05-25T21:12:01.513+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-25T21:12:01.513+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T21:12:01.520+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DAG_catedra_***, task_id=first-step-el, run_id=scheduled__2024-05-25T00:00:00+00:00, execution_date=20240525T000000, start_date=20240525T211201, end_date=20240525T211201
[2024-05-25T21:12:01.564+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-25T21:12:01.577+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T21:12:01.585+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
