[2024-05-26T01:03:47.063+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T01:03:47.088+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T02:20:00+00:00 [queued]>
[2024-05-26T01:03:47.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T02:20:00+00:00 [queued]>
[2024-05-26T01:03:47.096+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T01:03:47.111+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 02:20:00+00:00
[2024-05-26T01:03:47.120+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=480) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T01:03:47.121+0000] {standard_task_runner.py:63} INFO - Started process 490 to run task
[2024-05-26T01:03:47.122+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T02:20:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmphe9g9f5y']
[2024-05-26T01:03:47.123+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask second-step-el
[2024-05-26T01:03:47.172+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T02:20:00+00:00 [running]> on host bb8f67d70e6d
[2024-05-26T01:03:47.255+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T02:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T02:20:00+00:00'
[2024-05-26T01:03:47.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T01:03:47.263+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T01:03:47.267+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T01:03:47.267+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/Steps.py", line 16, in step_ingesta_transformacion_carga
    df=functions.SQL_query(host,database,user,password,port,extract_query,column_names_e)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/functions.py", line 31, in SQL_query
    df2.columns=column_names
    ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 21 elements, new values have 20 elements
[2024-05-26T01:03:47.280+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T02:20:00+00:00, execution_date=20240525T022000, start_date=20240526T010347, end_date=20240526T010347
[2024-05-26T01:03:47.293+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task second-step-el (Length mismatch: Expected axis has 21 elements, new values have 20 elements; 490)
[2024-05-26T01:03:47.337+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-26T01:03:47.351+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T01:03:47.355+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-26T02:01:28.572+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-26T02:01:28.601+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T02:20:00+00:00 [queued]>
[2024-05-26T02:01:28.615+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T02:20:00+00:00 [queued]>
[2024-05-26T02:01:28.616+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-26T02:01:28.639+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): second-step-el> on 2024-05-25 02:20:00+00:00
[2024-05-26T02:01:28.646+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=234) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-26T02:01:28.648+0000] {standard_task_runner.py:63} INFO - Started process 236 to run task
[2024-05-26T02:01:28.649+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_catedra_***', 'second-step-el', 'scheduled__2024-05-25T02:20:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_clase.py', '--cfg-path', '/tmp/tmpdy5zyk2z']
[2024-05-26T02:01:28.651+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask second-step-el
[2024-05-26T02:01:28.706+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_catedra_airflow.second-step-el scheduled__2024-05-25T02:20:00+00:00 [running]> on host da1b21f42040
[2024-05-26T02:01:28.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_catedra_***' AIRFLOW_CTX_TASK_ID='second-step-el' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T02:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-25T02:20:00+00:00'
[2024-05-26T02:01:28.827+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-26T02:01:28.834+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T02:01:28.850+0000] {logging_mixin.py:188} INFO - Query completed
[2024-05-26T02:01:28.856+0000] {logging_mixin.py:188} INFO - execute_query_result_set()
[2024-05-26T02:01:28.863+0000] {logging_mixin.py:188} INFO - The connection to the DB was succesful
[2024-05-26T02:01:28.870+0000] {logging_mixin.py:188} INFO - Inserts were comitted
[2024-05-26T02:01:28.871+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-26T02:01:28.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-26T02:01:28.882+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DAG_catedra_***, task_id=second-step-el, run_id=scheduled__2024-05-25T02:20:00+00:00, execution_date=20240525T022000, start_date=20240526T020128, end_date=20240526T020128
[2024-05-26T02:01:28.943+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-26T02:01:28.968+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26T02:01:28.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
